name: Daily snapshots

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  take-snapshots:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DEBUG: 'False'
      ALLOWED_HOSTS: '127.0.0.1,localhost'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: "pip"
          # cache-dependency-path: requirements-actions.txt
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements-actions.txt
          pip install -r requirements.txt
          
      - name: Run snapshot command
        run: |
          python manage.py take_snapshots
