name: Prod Snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  take-snapshots:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
      PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
      DEBUG: 'False'
      ALLOWED_HOSTS: "127.0.0.1,localhost,trackstack.uk,www.trackstack.uk"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: "pip"
          # cache-dependency-path: requirements-actions.txt
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements-actions.txt
          pip install -r requirements.txt
          
      - name: Run snapshot command
        run: |
          python manage.py take_snapshots
